-- Table to cache scraped lottery data (updated every 6 hours)
CREATE TABLE IF NOT EXISTS lottery_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game TEXT NOT NULL UNIQUE,
    data JSONB NOT NULL,
    analysis JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE lottery_cache ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read cache
CREATE POLICY "Public read cache" ON lottery_cache FOR SELECT USING (true);

-- Policy: Only service role can update
CREATE POLICY "Service update cache" ON lottery_cache FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Service insert cache" ON lottery_cache FOR INSERT WITH CHECK (auth.role() = 'service_role');
