-- ============================================================
-- CREAR TABLA DE HISTORIAL DE PREDICCIONES
-- ============================================================
-- Ejecuta esto en tu Supabase SQL Editor para guardar los resultados

CREATE TABLE IF NOT EXISTS prediction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game TEXT NOT NULL,
    numbers JSONB NOT NULL,    -- Guardará el array [1, 2, 3...]
    stars JSONB,               -- Guardará las estrellas si hay (Eurojackpot)
    confidence NUMERIC,        -- Nivel de confianza (0.85)
    license_key TEXT,          -- Qué clave generó esto (para rastrear usuarios)
    ai_reasoning TEXT,         -- La explicación que dio la IA
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar permisos (igual que antes)
ALTER TABLE prediction_history ENABLE ROW LEVEL SECURITY;

-- Permitir INSERTAR desde el backend (público/anónimo por ahora)
CREATE POLICY "Public Insert History" ON prediction_history FOR INSERT WITH CHECK (true);

-- Permitir LEER (opcional, si quieres mostrar historial en el frontend)
CREATE POLICY "Public Read History" ON prediction_history FOR SELECT USING (true);
