-- ============================================================
-- INSTRUCCIONES PARA CONFIGURAR SUPABASE
-- ============================================================
-- 1. Ve a tu Dashboard de Supabase -> SQL Editor (icono de terminal)
-- 2. Copia y pega el siguiente código
-- 3. Dale a "Run"

-- 1. Crear la tabla de licencias/claves
CREATE TABLE IF NOT EXISTS licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_code TEXT NOT NULL UNIQUE,
    credits INT DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Habilitar Row Level Security (Seguridad)
ALTER TABLE licenses ENABLE ROW LEVEL SECURITY;

-- 3. Crear políticas para permitir que tu App (Backend) lea y escriba
-- NOTA: Para producción real, deberías usar la SERVICE_ROLE_KEY en el servidor.
-- Como estamos usando la PUBLIC KEY que me diste, necesitamos permisos públicos 
-- (o podrías desactivar RLS, pero estas políticas son mejores).

-- Permitir LEER claves (para verificar si existen)
CREATE POLICY "Enable read access for all users" ON licenses
    FOR SELECT USING (true);

-- Permitir ACTUALIZAR créditos (para descontar usos)
CREATE POLICY "Enable update access for all users" ON licenses
    FOR UPDATE USING (true);

-- Permitir INSERTAR nuevas claves (para el admin)
CREATE POLICY "Enable insert access for all users" ON licenses
    FOR INSERT WITH CHECK (true);

-- ============================================================
-- DATOS DE PRUEBA (OPCIONAL)
-- ============================================================
-- Insertar una clave de prueba
INSERT INTO licenses (key_code, credits, active)
VALUES ('VIP-TEST-KEY', 10, true);
